version: "3.9"

services:
  users:
    image: mastermadriguera/solid-users-prod:latest
    container_name: users
    depends_on:
      - users_db
    environment:
      RMQ_HOST: amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@rabbitmq:5672
      DB_HOST: users_db
      DB_PORT: 3306
      DB_USER: ${MYSQL_ROOT_USER}
      DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      DB_NAME: ${USERS_SERVICE_DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
      ROLE_KEY: ${ROLE_KEY}
      GIT_CLIENT_ID: ${GIT_CLIENT_ID}
      GIT_CLIENT_SECRET: ${GIT_CLIENT_SECRET}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always

  general:
    image: mastermadriguera/solid-general-prod:latest
    container_name: general
    depends_on:
      - mongo_db
    environment:
      RMQ_HOST: amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@rabbitmq:5672
      DATABASE_NAME: ${GENERAL_SERVICE_DB_NAME}
      DATABASE_USER: ${MONGO_USER}
      DATABASE_PASS: ${MONGO_PASSWORD}
      DATABASE_URI: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongo_db:27017
      JWT_SECRET: ${JWT_SECRET}
      ROLE_KEY: ${ROLE_KEY}
      GIT_CLIENT_ID: ${GIT_CLIENT_ID}
      GIT_CLIENT_SECRET: ${GIT_CLIENT_SECRET}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3002/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always

  mongo_db:
    image: mastermadriguera/solid-mongo_db-prod:latest
    container_name: mongo_db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${GENERAL_SERVICE_DB_NAME}
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 5s
      timeout: 5s
      retries: 15
      start_period: 25s

  init-replica:
    image: mastermadriguera/solid-init-replica-prod:latest
    container_name: mongo_init_replica
    depends_on:
      mongo_db:
        condition: service_healthy
    environment:
      MONGO_USER: ${MONGO_USER}
      MONGO_PASS: ${MONGO_PASSWORD}

  gateway:
    image: mastermadriguera/solid-gateway-prod:latest
    container_name: gateway
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always

  stats:
    image: mastermadriguera/solid-stats-prod:latest
    environment:
      RMQ_HOST: amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@rabbitmq:5672
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      DATABASE_NAME: ${STATS_SERVICE_DB_NAME}
      DATABASE_USER: ${MONGO_USER}
      DATABASE_PASS: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongo_db:27017
      DATABASE_URI: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongo_db:27017
      JWT_SECRET: ${JWT_SECRET}
      ROLE_KEY: ${ROLE_KEY}
      GIT_CLIENT_ID: ${GIT_CLIENT_ID}
      GIT_CLIENT_SECRET: ${GIT_CLIENT_SECRET}
      ME_CONFIG_BASICAUTH: false
    container_name: stats
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3004/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always

  frontend:
    image: mastermadriguera/solid-frontend-prod:latest
    container_name: frontend
    restart: always

  users_db:
    image: mysql:latest
    container_name: users_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${USERS_SERVICE_DB_NAME}

  rabbitmq:
    image: rabbitmq:4-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    volumes:
      - ./rabbitmq/data:/var/lib/rabbitmq/
      - ./rabbitmq/log:/var/log/rabbitmq

volumes:
  db_data:
  db_mongo_data:
