---
- name: Configurar instancia EC2
  hosts: localhost
  become: true
  tasks:
    - name: Actualizar sistema
      yum:
        name: "*"
        state: latest

    - name: Instalar Docker
      yum:
        name: docker
        state: present

    - name: Iniciar y habilitar Docker
      systemd:
        name: docker
        state: started
        enabled: true

    - name: Instalar Git
      yum:
        name: git
        state: present

    - name: Verificar instalación
      shell: |
        docker --version
        docker-compose --version
        git --version

    - name: Verificar instalación de Git
      shell: |
        export PATH=$PATH:/usr/bin
        git --version
      register: git_version_result
      ignore_errors: true
    
    - name: Mostrar versión de Git
      debug:
        var: git_version_result.stdout
