---
- name: Configurar instancia EC2
  hosts: localhost
  become: true
  tasks:
    - name: Actualizar sistema
      yum:
        name: "*"
        state: latest

    - name: Instalar Docker
      yum:
        name: docker
        state: present

    - name: Iniciar y habilitar Docker
      systemd:
        name: docker
        state: started
        enabled: true

    - name: Instalar Git
      yum:
        name: git
        state: present

    - name: Instalar Python3 y pip (requerido para docker-compose vía pip)
      yum:
        name:
          - python3
          - python3-pip
          # - python3-setuptools  # si te hace falta
        state: present

    - name: Instalar Docker Compose mediante pip (usando pip3)
      pip:
        name: docker-compose
        state: latest
        executable: pip3

    - name: Verificar instalación
      shell: |
        echo "Docker:"
        docker --version
        echo "Docker Compose:"
        docker-compose --version
        echo "Git:"
        git --version

    - name: Agregar usuario actual al grupo docker
      user:
        name: "{{ ansible_user_id }}"
        groups: docker
        append: yes

    - name: Verificar instalación de Git
      shell: |
        export PATH=$PATH:/usr/bin
        git --version
      register: git_version_result
      ignore_errors: true
    
    - name: Mostrar versión de Git
      debug:
        var: git_version_result.stdout
